<a href="https://colab.research.google.com/github/farazkhanfk7/AI-Notebooks/blob/master/PyTorch/LinearRegressionPyTorchBuiltin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import torch.nn as nn
import numpy as np

In [6]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [7]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [8]:
from torch.utils.data import TensorDataset

In [9]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [10]:
from torch.utils.data import DataLoader

In [11]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [12]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.]])
tensor([[ 81., 101.],
        [103., 119.],
        [103., 119.],
        [ 56.,  70.],
        [119., 133.]])


# Creating Model

In [13]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0182, -0.3633,  0.4367],
        [ 0.2078, -0.4264, -0.4512]], requires_grad=True)
Parameter containing:
tensor([ 0.3460, -0.4517], requires_grad=True)


In [14]:
# PyTorch models also have a helpful .parameters method, which returns a list containing all the weights and bias matrices
list(model.parameters())

[Parameter containing:
 tensor([[-0.0182, -0.3633,  0.4367],
         [ 0.2078, -0.4264, -0.4512]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3460, -0.4517], requires_grad=True)]

In [15]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ -6.5447, -33.2546],
        [ -5.3310, -47.9440],
        [-24.5906, -65.6839],
        [ -0.9723, -14.2877],
        [ -5.2176, -58.6336],
        [ -6.5447, -33.2546],
        [ -5.3310, -47.9440],
        [-24.5906, -65.6839],
        [ -0.9723, -14.2877],
        [ -5.2176, -58.6336],
        [ -6.5447, -33.2546],
        [ -5.3310, -47.9440],
        [-24.5906, -65.6839],
        [ -0.9723, -14.2877],
        [ -5.2176, -58.6336]], grad_fn=<AddmmBackward>)

# Loss function

In [16]:
# Import nn.functional
import torch.nn.functional as F

In [17]:
# Define loss function
loss_fn = F.mse_loss

In [18]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(15072.7188, grad_fn=<MseLossBackward>)


# Optimizer

In [19]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [20]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # Generate predictions
            pred = model(xb)
            
            # Calculate loss
            loss = loss_fn(pred, yb)
            
            # Compute gradients
            loss.backward()
            
            # Update parameters using gradients
            opt.step()
            
            # Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [22]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 785.2225
Epoch [20/100], Loss: 416.8676
Epoch [30/100], Loss: 298.2567
Epoch [40/100], Loss: 373.6209
Epoch [50/100], Loss: 132.6616
Epoch [60/100], Loss: 118.6062
Epoch [70/100], Loss: 72.7608
Epoch [80/100], Loss: 93.2786
Epoch [90/100], Loss: 36.1422
Epoch [100/100], Loss: 42.4262


In [23]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.3441,  72.1305],
        [ 83.6915,  96.9790],
        [113.0580, 137.6042],
        [ 27.9568,  48.1934],
        [100.5854, 106.1640],
        [ 58.3441,  72.1305],
        [ 83.6915,  96.9790],
        [113.0580, 137.6042],
        [ 27.9568,  48.1934],
        [100.5854, 106.1640],
        [ 58.3441,  72.1305],
        [ 83.6915,  96.9790],
        [113.0580, 137.6042],
        [ 27.9568,  48.1934],
        [100.5854, 106.1640]], grad_fn=<AddmmBackward>)

In [24]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])